
#include <SI_EFM8LB1_Register_Enums.h>
#include "InitDevice.h"


extern void enter_BusFreeMode_from_RESET(void) {
	uint8_t SFRPAGE_save = SFRPAGE;
	CLOCK_0_enter_BusFreeMode_from_RESET();

	SFRPAGE = SFRPAGE_save;

}

extern void PORTS_2_enter_BusFreeMode_from_RESET(void) {
	SFRPAGE = 0x00;
	P2MDOUT = P2MDOUT_B0__OPEN_DRAIN | P2MDOUT_B1__OPEN_DRAIN
			| P2MDOUT_B2__OPEN_DRAIN | P2MDOUT_B3__PUSH_PULL
			| P2MDOUT_B4__OPEN_DRAIN | P2MDOUT_B5__OPEN_DRAIN
			| P2MDOUT_B6__OPEN_DRAIN;
	SFRPAGE = 0x20;
	P2SKIP = P2SKIP_B0__NOT_SKIPPED | P2SKIP_B1__NOT_SKIPPED
			| P2SKIP_B2__NOT_SKIPPED | P2SKIP_B3__SKIPPED;

}

extern void PBCFG_0_enter_BusFreeMode_from_RESET(void) {

}

extern void CIP51_0_enter_BusFreeMode_from_RESET(void) {

}

extern void CLOCK_0_enter_BusFreeMode_from_RESET(void) {
	SFRPAGE = 0x00;
	CLKSEL = CLKSEL_CLKSL__HFOSC0 | CLKSEL_CLKDIV__SYSCLK_DIV_1;
	while ((CLKSEL & CLKSEL_DIVRDY__BMASK) == CLKSEL_DIVRDY__NOT_READY)
		;


}

extern void enter_DefaultMode_from_BusFreeMode(void) {
	uint8_t SFRPAGE_save = SFRPAGE;
	WDT_0_enter_DefaultMode_from_BusFreeMode();
	PORTS_0_enter_DefaultMode_from_BusFreeMode();
	PORTS_1_enter_DefaultMode_from_BusFreeMode();
	PBCFG_0_enter_DefaultMode_from_BusFreeMode();
	ADC_0_enter_DefaultMode_from_BusFreeMode();
	TIMER01_0_enter_DefaultMode_from_BusFreeMode();
	TIMER16_3_enter_DefaultMode_from_BusFreeMode();
	TIMER16_4_enter_DefaultMode_from_BusFreeMode();
	TIMER16_5_enter_DefaultMode_from_BusFreeMode();
	TIMER_SETUP_0_enter_DefaultMode_from_BusFreeMode();
	SMBUS_0_enter_DefaultMode_from_BusFreeMode();
	UARTE_1_enter_DefaultMode_from_BusFreeMode();
	I2CSLAVE_0_enter_DefaultMode_from_BusFreeMode();
	INTERRUPT_0_enter_DefaultMode_from_BusFreeMode();
	SFRPAGE = SFRPAGE_save;

}

extern void WDT_0_enter_DefaultMode_from_BusFreeMode(void) {
	SFRPAGE = 0x00;
	WDTCN = 0xDE; 
	WDTCN = 0xAD; 


}

extern void PORTS_0_enter_DefaultMode_from_BusFreeMode(void) {

	P0SKIP = P0SKIP_B0__SKIPPED | P0SKIP_B1__SKIPPED | P0SKIP_B2__SKIPPED
			| P0SKIP_B3__SKIPPED | P0SKIP_B4__SKIPPED | P0SKIP_B5__SKIPPED
			| P0SKIP_B6__SKIPPED | P0SKIP_B7__SKIPPED;

}

extern void PORTS_1_enter_DefaultMode_from_BusFreeMode(void) {
	P1MDOUT = P1MDOUT_B0__OPEN_DRAIN | P1MDOUT_B1__OPEN_DRAIN
			| P1MDOUT_B2__OPEN_DRAIN | P1MDOUT_B3__OPEN_DRAIN
			| P1MDOUT_B4__PUSH_PULL | P1MDOUT_B5__OPEN_DRAIN
			| P1MDOUT_B6__PUSH_PULL | P1MDOUT_B7__OPEN_DRAIN;

	P1SKIP = P1SKIP_B0__SKIPPED | P1SKIP_B1__SKIPPED | P1SKIP_B2__NOT_SKIPPED
			| P1SKIP_B3__NOT_SKIPPED | P1SKIP_B4__NOT_SKIPPED
			| P1SKIP_B5__NOT_SKIPPED | P1SKIP_B6__NOT_SKIPPED
			| P1SKIP_B7__NOT_SKIPPED;

}

extern void PBCFG_0_enter_DefaultMode_from_BusFreeMode(void) {
	XBR2 = XBR2_WEAKPUD__PULL_UPS_ENABLED | XBR2_XBARE__ENABLED
			| XBR2_URT1E__ENABLED | XBR2_URT1RTSE__DISABLED
			| XBR2_URT1CTSE__DISABLED;
	XBR0 = XBR0_URT0E__DISABLED | XBR0_SPI0E__DISABLED | XBR0_SMB0E__ENABLED
			| XBR0_CP0E__DISABLED | XBR0_CP0AE__DISABLED | XBR0_CP1E__DISABLED
			| XBR0_CP1AE__DISABLED | XBR0_SYSCKE__DISABLED;

}

extern void TIMER01_0_enter_DefaultMode_from_BusFreeMode(void) {
	uint8_t TCON_save;
	TCON_save = TCON;

	TCON &= ~TCON_TR0__BMASK & ~TCON_TR1__BMASK;

	TH0 = (0x38 << TH0_TH0__SHIFT);
	TL0 = (0x13 << TL0_TL0__SHIFT);
	TH1 = (0xFA << TH1_TH1__SHIFT);
	TL1 = (0x34 << TL1_TL1__SHIFT);
	TCON |= (TCON_save & TCON_TR0__BMASK) | (TCON_save & TCON_TR1__BMASK);



}

extern void TIMER16_3_enter_DefaultMode_from_BusFreeMode(void) {
	uint8_t TMR3CN0_TR3_save;
	TMR3CN0_TR3_save = TMR3CN0 & TMR3CN0_TR3__BMASK;

	TMR3CN0 &= ~(TMR3CN0_TR3__BMASK);
	TMR3H = (0xFE << TMR3H_TMR3H__SHIFT);
	TMR3L = (0x0C << TMR3L_TMR3L__SHIFT);
	TMR3RLH = (0x38 << TMR3RLH_TMR3RLH__SHIFT);
	TMR3RLL = (0x9E << TMR3RLL_TMR3RLL__SHIFT);
	TMR3CN0 |= TMR3CN0_TR3__RUN;
	TMR3CN0 |= TMR3CN0_TR3_save;


}

extern void TIMER_SETUP_0_enter_DefaultMode_from_BusFreeMode(void) {
	SFRPAGE = 0x00;
	CKCON0 = CKCON0_SCA__SYSCLK_DIV_4 | CKCON0_T0M__PRESCALE
			| CKCON0_T2MH__EXTERNAL_CLOCK | CKCON0_T2ML__EXTERNAL_CLOCK
			| CKCON0_T3MH__EXTERNAL_CLOCK | CKCON0_T3ML__EXTERNAL_CLOCK
			| CKCON0_T1M__PRESCALE;
	TMOD = TMOD_T0M__MODE0 | TMOD_T1M__MODE2 | TMOD_CT0__TIMER
			| TMOD_GATE0__DISABLED | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;
	TCON |= TCON_TR1__RUN;


}

extern void SMBUS_0_enter_DefaultMode_from_BusFreeMode(void) {

	SMB0CF &= ~SMB0CF_SMBCS__FMASK;
	SMB0CF |= SMB0CF_SMBCS__TIMER1 | SMB0CF_INH__SLAVE_DISABLED
			| SMB0CF_ENSMB__ENABLED | SMB0CF_SMBFTE__FREE_TO_ENABLED
			| SMB0CF_SMBTOE__SCL_TO_ENABLED | SMB0CF_EXTHOLD__ENABLED;


}

extern void INTERRUPT_0_enter_DefaultMode_from_BusFreeMode(void) {
	SFRPAGE = 0x00;
	EIE1 = EIE1_EADC0__ENABLED | EIE1_EWADC0__DISABLED | EIE1_ECP0__DISABLED
			| EIE1_ECP1__DISABLED | EIE1_EMAT__DISABLED | EIE1_EPCA0__DISABLED
			| EIE1_ESMB0__ENABLED | EIE1_ET3__ENABLED;
	EIE2 = EIE2_CL0__DISABLED | EIE2_EI2C0__ENABLED | EIE2_ET4__ENABLED
			| EIE2_ET5__DISABLED | EIE2_ES1__DISABLED;

	IE = IE_EA__ENABLED | IE_EX0__DISABLED | IE_EX1__DISABLED
			| IE_ESPI0__DISABLED | IE_ET0__DISABLED | IE_ET1__DISABLED
			| IE_ET2__DISABLED | IE_ES0__DISABLED;

}

extern void UARTE_1_enter_DefaultMode_from_BusFreeMode(void) {
	SBRLH1 = (0xFF << SBRLH1_BRH__SHIFT);
	SBRLL1 = (0x96 << SBRLL1_BRL__SHIFT);
	SCON1 |= SCON1_REN__RECEIVE_ENABLED;

}

extern void TIMER16_4_enter_DefaultMode_from_BusFreeMode(void) {
	uint8_t TMR4CN0_TR4_save;
	SFRPAGE = 0x10;
	TMR4CN0_TR4_save = TMR4CN0 & TMR4CN0_TR4__BMASK;

	TMR4CN0 &= ~(TMR4CN0_TR4__BMASK);

	TMR4RLH = (0x38 << TMR4RLH_TMR4RLH__SHIFT);
	TMR4RLL = (0x9E << TMR4RLL_TMR4RLL__SHIFT);
	TMR4CN0 |= TMR4CN0_TR4__RUN;
	TMR4CN0 |= TMR4CN0_TR4_save;


}

extern void I2CSLAVE_0_enter_DefaultMode_from_BusFreeMode(void) {
	I2C0SLAD = (0x50 << I2C0SLAD_I2C0SLAD__SHIFT);
	I2C0CN0 &= ~I2C0CN0_PRELOAD__BMASK;
	I2C0CN0 |= I2C0CN0_PINMD__I2C_MODE | I2C0CN0_TIMEOUT__ENABLED;
	I2C0CN0 |= I2C0CN0_I2C0EN__ENABLED;

}

extern void ADC_0_enter_DefaultMode_from_BusFreeMode(void) {
	ADC0CN2 = ADC0CN2_ADCM__TIMER5 | ADC0CN2_PACEN__PAC_DISABLED;
	ADC0CN1 = ADC0CN1_ADBITS__14_BIT | ADC0CN1_ADSJST__RIGHT_SHIFT_3
			| ADC0CN1_ADRPT__ACC_32;
	ADC0MX = ADC0MX_ADC0MX__TEMP;
	ADC0CF2 = ADC0CF2_GNDSL__GND_PIN | ADC0CF2_REFSL__INTERNAL_VREF
			| (0x03 << ADC0CF2_ADPWR__SHIFT);
	ADC0CF0 = ADC0CF0_ADCLKSEL__SYSCLK | (0x01 << ADC0CF0_ADSC__SHIFT);
	ADC0CF1 = ADC0CF1_ADLPM__LP_ENABLED | (0x06 << ADC0CF1_ADTK__SHIFT);

	ADC0CN0 |= ADC0CN0_ADEN__ENABLED | ADC0CN0_TEMPE__TEMP_ENABLED
			| ADC0CN0_IPOEN__POWER_DOWN;


}

extern void TIMER16_5_enter_DefaultMode_from_BusFreeMode(void) {
	uint8_t TMR5CN0_TR5_save;
	TMR5CN0_TR5_save = TMR5CN0 & TMR5CN0_TR5__BMASK;

	TMR5CN0 &= ~(TMR5CN0_TR5__BMASK);

	TMR5CN0 |= TMR5CN0_TR5__RUN;
	TMR5CN0 |= TMR5CN0_TR5_save;

}

